### ISSUE TITLE
ux research

### ISSUE THREAD

**Issue by particle4dev** [KMDice/kmdice-wallet#1]
EOS Dice Bet

- https://www.youtube.com/watch?v=wfoIN6yC6m8

Tutorial

- https://medium.com/@eosplay/how-to-create-an-eos-account-for-eos-dice-9be2f16a2691

UI

![EOS Dice Bet](https://i.pinimg.com/564x/45/4b/da/454bda48e8dc7fd1003696cd9db33294.jpg "EOS Dice Bet")

![EOS Dice Bet](https://cdn.stateofthedapps.com/dapps/eosbet-dice/product_image_eosbet-dice_bbd2663c010c341f7883cac81afbd5089d888254630ba2373697666ad39da81f_opti.png "EOS Dice Bet")

**Comment by siulynot** [comment]
Lucky Games is another UX

https://luckygames.io/?game=dice

The UX is very ugly and they say the have more that 64BILLION bets done which is hard to believe, but just to offer different approaches

<img src="http://i.imgur.com/q45zRIm.png"/>

**Comment by siulynot** [comment]
Also we have the classic crypto dice game which is
https://satoshidice.com

but this game is not blockchain based, although many people has had the experience of playing it, so the UX is familiar with many:

<img src="http://i.imgur.com/Vm2qdMo.png"/>

**Comment by siulynot** [comment]
And finally, we have a hybrid from luckygame and eosbet
https://endless.game/
This version has the big numbers, the toggle for selecting odds and a space to input bet size:

<img src="http://i.imgur.com/MwzPuMK.png"/>

**Comment by particle4dev** [comment]
https://dribbble.com/shots/5644834-Gambling-page
![gambling page](https://cdn.dribbble.com/users/2186832/screenshots/5644834/____06_2x.png "gambling page")

**Comment by particle4dev** [comment]
https://www.stateofthedapps.com/dapps/bet24
